name: Auto-label Issues

on:
  issues:
    types: [opened, edited]

jobs:
  label-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read

    steps:
      - name: Label Issue with LLM
        uses: ./ # Use ./ for local action, or your-username/repo-name@v1 for published action
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          openai-endpoint: ${{ secrets.OPENAI_ENDPOINT }}
          openai-model: ${{ secrets.OPENAI_MODEL }}
          custom-labels: |
            [
              {
                "label": "security",
                "description": "Security-related issues or vulnerabilities"
              },
              {
                "label": "performance",
                "description": "Performance optimization or issues"
              },
              {
                "label": "ui/ux",
                "description": "User interface or user experience related"
              }
            ]
